version: "3"
services:
  db-jefiwash:
    image: postgres:15
    container_name: jefiwash
    hostname: jefiwash
    restart: always
    ports:
      - 5438:5433
    volumes:
      - .db:/var/lib/postgresql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jefiwash

  backend-jefiwash:
    image: tomasjef/backend-jefiwash
    ports:
       - 8080:8080
    depends_on:
       - db-jefiwash
    env_file:
       - ./.env
    container_name: backend-jefiwash

  frontend-jefiwash:
    image: tomasjef/frontend-jefiwash
    ports:
       - 3000:3000
    depends_on:
        - backend-jefiwash
    container_name: frontend-jefiwash